"""Export adapters: JSON, PDF and a FHIR-*compatible* JSON bundle.

The FHIR adapter produces resources shaped according to FHIR R4 for the subset
MedScribe populates. It is deliberately described as "FHIR-compatible": it has
not been validated against a conformance server, and no claim of full compliance
is made.
"""

from __future__ import annotations

import io
import json
import uuid
from datetime import datetime, timezone
from typing import Any

from app.models.enums import EntityStatus, EntityType
from app.schemas.clinical import SECTION_KEYS, SECTION_LABELS, ClinicalNoteContent

FHIR_VERSION = "4.0.1"
DISCLAIMER = (
    "Generated by MedScribe Live. Not a diagnostic record. AI-assisted documentation "
    "requires human review; model confidence is not a measure of clinical correctness."
)


_UNDOCUMENTED_PHRASES = {
    "not mentioned",
    "not found",
    "not stated",
    "not discussed",
    "none mentioned",
    "not available",
    "n/a",
    "na",
    "none",
    "unknown",
}


def _section_documented(section: dict[str, Any] | None) -> bool:
    text = str((section or {}).get("text") or "").strip()
    return bool(text) and text.lower() not in _UNDOCUMENTED_PHRASES


def build_export_payload(
    *,
    session: dict[str, Any],
    note: dict[str, Any],
    segments: list[dict[str, Any]],
    entities: list[dict[str, Any]],
    evidence: list[dict[str, Any]],
    versions: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "export_format": "MEDSCRIBE_JSON_V1",
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": DISCLAIMER,
        "session": session,
        "clinical_note": note,
        "transcript": segments,
        "clinical_entities": entities,
        "evidence_links": evidence,
        "note_versions": versions or [],
    }


def export_json(payload: dict[str, Any]) -> bytes:
    return json.dumps(payload, indent=2, default=str).encode("utf-8")


# ----------------------------------------------------------------------- PDF
def export_pdf(payload: dict[str, Any]) -> bytes:
    """Render the note, its evidence counts and the transcript to a PDF."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        HRFlowable,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    session = payload.get("session", {})
    note = payload.get("clinical_note", {})
    content = note.get("content", {})
    entities: list[dict[str, Any]] = payload.get("clinical_entities", [])
    segments: list[dict[str, Any]] = payload.get("transcript", [])

    styles = getSampleStyleSheet()
    navy = colors.HexColor("#0f2942")
    teal = colors.HexColor("#0f766e")
    title_style = ParagraphStyle("MSTitle", parent=styles["Title"], textColor=navy, fontSize=18, spaceAfter=4)
    meta_style = ParagraphStyle("MSMeta", parent=styles["Normal"], fontSize=8.5, textColor=colors.HexColor("#475569"))
    heading_style = ParagraphStyle(
        "MSHeading", parent=styles["Heading2"], textColor=teal, fontSize=11.5, spaceBefore=10, spaceAfter=3
    )
    body_style = ParagraphStyle("MSBody", parent=styles["BodyText"], fontSize=9.5, leading=13, alignment=TA_LEFT)
    small_style = ParagraphStyle("MSSmall", parent=styles["Normal"], fontSize=7.8, textColor=colors.HexColor("#64748b"))

    buffer = io.BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=f"MedScribe Live - {session.get('reference', 'session')}",
        author="MedScribe Live",
    )

    story: list[Any] = [
        Paragraph("MedScribe Live - Clinical Note", title_style),
        Paragraph(DISCLAIMER, meta_style),
        Spacer(1, 6),
        HRFlowable(width="100%", color=colors.HexColor("#cbd5e1")),
        Spacer(1, 6),
    ]

    meta_rows = [
        ["Session", session.get("reference", "-"), "Status", str(note.get("status", "-"))],
        ["Name", session.get("name", "-"), "Note version", str(note.get("version", 0))],
        ["Patient", session.get("patient_id", "-"), "Model", str(note.get("model", "-"))],
        ["Clinician", session.get("doctor_name") or "-", "Faculty", session.get("faculty_name") or "-"],
        [
            "Started",
            str(session.get("started_at") or "-"),
            "Approved by",
            str(note.get("approved_by") or "Not approved"),
        ],
    ]
    meta_table = Table(meta_rows, colWidths=[32 * mm, 58 * mm, 28 * mm, 46 * mm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 8.2),
                ("TEXTCOLOR", (0, 0), (0, -1), navy),
                ("TEXTCOLOR", (2, 0), (2, -1), navy),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#e2e8f0")),
            ]
        )
    )
    story += [meta_table, Spacer(1, 8)]

    for key in SECTION_KEYS:
        section = content.get(key) or {}
        if not _section_documented(section):
            continue
        text = section.get("text") or ""
        evidence_count = len(section.get("evidence") or [])
        confidence = float(section.get("confidence") or 0.0)
        flag = " [REVIEW REQUIRED]" if section.get("review_required") else ""
        edited = " [human edited]" if section.get("edited_by_human") else ""
        story.append(Paragraph(f"{SECTION_LABELS[key]}{flag}{edited}", heading_style))
        story.append(Paragraph(text, body_style))
        story.append(
            Paragraph(
                f"Evidence references: {evidence_count} &nbsp;|&nbsp; extraction confidence: {confidence * 100:.0f}%",
                small_style,
            )
        )

    grouped: dict[str, list[dict[str, Any]]] = {}
    for entity in entities:
        grouped.setdefault(str(entity.get("entity_type")), []).append(entity)

    if grouped:
        story += [Spacer(1, 8), Paragraph("Structured Clinical Data", heading_style)]
        rows = [["Type", "Value", "Status", "Confidence", "Evidence"]]
        for entity_type in sorted(grouped):
            for entity in grouped[entity_type]:
                rows.append(
                    [
                        entity_type.replace("_", " ").title(),
                        str(entity.get("value", ""))[:60],
                        str(entity.get("status", "")),
                        f"{float(entity.get('confidence') or 0) * 100:.0f}%",
                        ", ".join(entity.get("source_segment_refs") or []) or "-",
                    ]
                )
        table = Table(rows, colWidths=[30 * mm, 58 * mm, 24 * mm, 20 * mm, 32 * mm], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), navy),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 7.6),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ]
            )
        )
        story.append(table)

    if segments:
        story += [PageBreak(), Paragraph("Source Transcript (evidence)", heading_style)]
        for segment in segments:
            timestamp = _format_timestamp(segment.get("start_time", 0.0))
            role = str(segment.get("role", "UNKNOWN"))
            story.append(
                Paragraph(
                    f"<b>[{segment.get('ref')}] {role}</b> {timestamp} "
                    f"({float(segment.get('confidence') or 0) * 100:.0f}% transcription confidence)",
                    small_style,
                )
            )
            story.append(Paragraph(str(segment.get("text", "")), body_style))

    document.build(story)
    return buffer.getvalue()


def _format_timestamp(seconds: float) -> str:
    seconds = max(0.0, float(seconds or 0))
    minutes, secs = divmod(int(seconds), 60)
    hours, minutes = divmod(minutes, 60)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"


# ---------------------------------------------------------------------- FHIR
class FHIRAdapter:
    """Maps a MedScribe session onto a FHIR-compatible R4 bundle."""

    OBSERVATION_TYPES = {
        EntityType.SYMPTOM,
        EntityType.FINDING,
        EntityType.SEVERITY,
        EntityType.FREQUENCY,
        EntityType.DURATION,
        EntityType.CHARACTER,
    }

    def build_bundle(
        self,
        *,
        session: dict[str, Any],
        note: dict[str, Any],
        entities: list[dict[str, Any]],
        segments: list[dict[str, Any]],
    ) -> dict[str, Any]:
        patient_id = f"patient-{_slug(session.get('patient_id', 'sim'))}"
        encounter_id = f"encounter-{_slug(session.get('reference', 'sim'))}"
        recorded = note.get("updated_at") or datetime.now(timezone.utc).isoformat()

        resources: list[dict[str, Any]] = [
            self._patient(patient_id, session),
            self._encounter(encounter_id, patient_id, session),
        ]

        for entity in entities:
            entity_type = _as_entity_type(entity.get("entity_type"))
            if entity_type is None:
                continue
            if entity_type in self.OBSERVATION_TYPES:
                resources.append(self._observation(entity, patient_id, encounter_id, recorded))
            elif entity_type is EntityType.MEDICATION:
                resources.append(self._medication_statement(entity, patient_id, encounter_id, recorded))
            elif entity_type is EntityType.ALLERGY:
                resources.append(self._allergy(entity, patient_id, recorded))
            elif entity_type is EntityType.INVESTIGATION:
                resources.append(self._service_request(entity, patient_id, encounter_id, recorded))
            elif entity_type in (EntityType.PLAN, EntityType.FOLLOW_UP):
                resources.append(self._care_plan(entity, patient_id, encounter_id, recorded))

        resources.append(self._diagnostic_report(note, patient_id, encounter_id, recorded, len(segments)))

        return {
            "resourceType": "Bundle",
            "id": f"medscribe-{_slug(session.get('reference', 'sim'))}",
            "type": "collection",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "meta": {
                "profile": [],
                "tag": [
                    {"system": "http://medscribe.local/tags", "code": "encounter", "display": "Clinical encounter"},
                    {
                        "system": "http://medscribe.local/tags",
                        "code": "fhir-compatible",
                        "display": f"FHIR {FHIR_VERSION} compatible subset - not conformance validated",
                    },
                ],
            },
            "entry": [{"fullUrl": f"urn:uuid:{uuid.uuid4()}", "resource": resource} for resource in resources],
        }

    # ------------------------------------------------------------- resources
    @staticmethod
    def _patient(patient_id: str, session: dict[str, Any]) -> dict[str, Any]:
        return {
            "resourceType": "Patient",
            "id": patient_id,
            "identifier": [
                {
                    "system": "http://medscribe.local/patient",
                    "value": str(session.get("patient_id", "unknown")),
                }
            ],
            "active": True,
            "name": [{"use": "anonymous", "text": "Patient"}],
        }

    @staticmethod
    def _encounter(encounter_id: str, patient_id: str, session: dict[str, Any]) -> dict[str, Any]:
        return {
            "resourceType": "Encounter",
            "id": encounter_id,
            "status": "finished" if session.get("ended_at") else "in-progress",
            "class": {
                "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
                "code": "AMB",
                "display": "ambulatory",
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "period": {"start": session.get("started_at"), "end": session.get("ended_at")},
            "reasonCode": [{"text": session.get("scenario") or "Clinical encounter"}],
        }

    @staticmethod
    def _observation(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        status = str(entity.get("status", "UNKNOWN"))
        resource = {
            "resourceType": "Observation",
            "id": f"observation-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "preliminary",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                            "code": "exam",
                        }
                    ]
                }
            ],
            "code": _codeable(entity),
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "effectiveDateTime": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }
        if status == "NEGATED":
            resource["valueCodeableConcept"] = {
                "coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0136", "code": "N"}],
                "text": "Explicitly denied by the speaker",
            }
        elif status == "UNCERTAIN":
            resource["dataAbsentReason"] = {"text": "Uncertain - hedged statement, not confirmed"}
        return resource

    @staticmethod
    def _medication_statement(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        return {
            "resourceType": "MedicationStatement",
            "id": f"medication-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "recorded" if str(entity.get("status")) != "NEGATED" else "not-taken",
            "medicationCodeableConcept": _codeable(entity),
            "subject": {"reference": f"Patient/{patient_id}"},
            "context": {"reference": f"Encounter/{encounter_id}"},
            "dateAsserted": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _allergy(entity: dict[str, Any], patient_id: str, recorded: str) -> dict[str, Any]:
        negated = str(entity.get("status")) == "NEGATED"
        return {
            "resourceType": "AllergyIntolerance",
            "id": f"allergy-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "clinicalStatus": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
                        "code": "inactive" if negated else "active",
                    }
                ]
            },
            "verificationStatus": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
                        "code": "refuted" if negated else "unconfirmed",
                    }
                ]
            },
            "code": _codeable(entity),
            "patient": {"reference": f"Patient/{patient_id}"},
            "recordedDate": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _service_request(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        return {
            "resourceType": "ServiceRequest",
            "id": f"servicerequest-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "draft",
            "intent": "proposal",
            "code": _codeable(entity),
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "authoredOn": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _care_plan(
        entity: dict[str, Any], patient_id: str, encounter_id: str, recorded: str
    ) -> dict[str, Any]:
        return {
            "resourceType": "CarePlan",
            "id": f"careplan-{_slug(entity.get('ref', uuid.uuid4().hex))}",
            "status": "draft",
            "intent": "proposal",
            "title": str(entity.get("entity_type", "PLAN")).replace("_", " ").title(),
            "description": str(entity.get("value", "")),
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "created": recorded,
            "note": [{"text": _provenance_text(entity)}],
        }

    @staticmethod
    def _diagnostic_report(
        note: dict[str, Any], patient_id: str, encounter_id: str, recorded: str, segment_count: int
    ) -> dict[str, Any]:
        content = note.get("content", {})
        lines = []
        for key in SECTION_KEYS:
            section = content.get(key) or {}
            if not _section_documented(section):
                continue
            lines.append(f"{SECTION_LABELS[key]}: {section.get('text')}")
        narrative = "<div xmlns=\"http://www.w3.org/1999/xhtml\">" + "".join(
            f"<p>{_escape(line)}</p>" for line in lines
        ) + f"<p><em>{_escape(DISCLAIMER)}</em></p></div>"
        return {
            "resourceType": "DiagnosticReport",
            "id": f"report-{_slug(str(note.get('id', uuid.uuid4().hex)))}",
            "status": "preliminary" if str(note.get("status")) != "APPROVED" else "final",
            "code": {"text": "AI-assisted clinical documentation"},
            "subject": {"reference": f"Patient/{patient_id}"},
            "encounter": {"reference": f"Encounter/{encounter_id}"},
            "issued": recorded,
            "conclusion": (
                (content.get("assessment") or {}).get("text")
                if _section_documented(content.get("assessment"))
                else None
            ),
            "text": {"status": "generated", "div": narrative},
            "extension": [
                {
                    "url": "http://medscribe.local/StructureDefinition/transcript-segment-count",
                    "valueInteger": segment_count,
                },
                {
                    "url": "http://medscribe.local/StructureDefinition/note-version",
                    "valueInteger": int(note.get("version") or 0),
                },
            ],
        }


def _codeable(entity: dict[str, Any]) -> dict[str, Any]:
    """Only emit a coding when a verified code exists - never fabricate one."""
    text = str(entity.get("normalized_value") or entity.get("value") or "")
    code = entity.get("normalized_code")
    system = entity.get("terminology_system")
    if code and system:
        return {"coding": [{"system": _system_url(system), "code": code, "display": text}], "text": text}
    return {"text": text}


def _system_url(system: str) -> str:
    return {
        "SNOMED-CT": "http://snomed.info/sct",
        "ICD-10": "http://hl7.org/fhir/sid/icd-10",
        "RxNorm": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "LOINC": "http://loinc.org",
    }.get(system, f"http://medscribe.local/{_slug(system)}")


def _provenance_text(entity: dict[str, Any]) -> str:
    refs = ", ".join(entity.get("source_segment_refs") or []) or "none"
    return (
        f"Status: {entity.get('status')}. Extraction confidence: "
        f"{float(entity.get('confidence') or 0) * 100:.0f}%. Transcript evidence: {refs}. "
        "Requires human review."
    )


def _as_entity_type(value: Any) -> EntityType | None:
    if isinstance(value, EntityType):
        return value
    try:
        return EntityType(str(value))
    except ValueError:
        return None


def _slug(value: Any) -> str:
    text = str(value).lower()
    return "".join(char if char.isalnum() else "-" for char in text).strip("-") or "unknown"


def _escape(value: str) -> str:
    return (
        value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def note_status_is_approved(note: dict[str, Any]) -> bool:
    return str(note.get("status")) == "APPROVED"


def entity_status_label(status: Any) -> str:
    try:
        return EntityStatus(str(status)).value
    except ValueError:
        return "UNKNOWN"


def empty_note_content() -> dict[str, Any]:
    return ClinicalNoteContent().model_dump(mode="json")
